Добавляет файл schema.sql с SQL-кодом для создания схемы БД проекта yeticave
htmlacademy-php/1637193-yeticave-12 pull request #15
Opened 2020-10-31 14:24 UTC by al-galkin

https://up.htmlacademy.ru/php/12/tasks/9

2020-11-02 06:24 UTC, mihan007 requested changes
Александр, проделана большая работа, видно, что в теме разобрался. Я пока проверил на уровне загрузки этого файла в локальную БД. Пока не загрузилось из-за ошибок. Жду обновленный PR, загружу его и дам следующие комментарии.

2020-11-02 06:24 UTC, mihan007 commented on schema.sql
> +                                                        UNIQUE INDEX `title_UNIQUE` (`category_title` ASC) VISIBLE)
[ERROR in query 6] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'VISIBLE)
    ENGINE = InnoDB' at line 9

2020-11-02 06:24 UTC, mihan007 commented on schema.sql
> +                                                    `creation_date` TIMESTAMP(14) NOT NULL,
[ERROR in query 7] Too-big precision 14 specified for 'creation_date'. Maximum is 6.

2020-11-02 06:24 UTC, mihan007 commented on schema.sql
> +                                                   `bet_date` TIMESTAMP(14) NOT NULL,
[ERROR in query 8] Too-big precision 14 specified for 'bet_date'. Maximum is 6.

2020-11-02 06:24 UTC, mihan007 commented on schema.sql
> +                                                    `registration_date` TIMESTAMP(14) NOT NULL,
[ERROR in query 9] Too-big precision 14 specified for 'registration_date'. Maximum is 6.

2020-11-02 06:24 UTC, mihan007 commented on schema.sql
> +                                                    UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
[ERROR in query 10] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'VISIBLE,
                                                           INDEX `item_' at line 9

2020-11-02 06:24 UTC, mihan007 commented on schema.sql
> +                                                           INDEX `user_idx` (`user_id` ASC) VISIBLE,
[ERROR in query 11] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'VISIBLE,
                                                           INDEX `item_' at line 9

2020-11-02 06:24 UTC, mihan007 commented on schema.sql
> +                                                           INDEX `item_idx` (`item_id` ASC) VISIBLE,
[ERROR in query 11] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'VISIBLE,
                                                           INDEX `item_' at line 9

2020-11-02 06:24 UTC, mihan007 commented on schema.sql
> +                                                           INDEX `user_idx` (`user_id` ASC) VISIBLE,
[ERROR in query 12] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'VISIBLE,
                                                             INDEX `ite' at line 8

2020-11-02 06:24 UTC, mihan007 commented on schema.sql
> +                                                           INDEX `item_idx` (`item_id` ASC) VISIBLE,
[ERROR in query 12] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'VISIBLE,
                                                             INDEX `ite' at line 8

2020-11-02 06:24 UTC, mihan007 commented on schema.sql
> +                                                             INDEX `category_idx` (`category_id` ASC) VISIBLE,
[ERROR in query 13] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'VISIBLE,
                                                        INDEX `bet_idx`' at line 10

2020-11-02 06:24 UTC, mihan007 commented on schema.sql
> +                                                             INDEX `item_idx` (`item_id` ASC) VISIBLE,
[ERROR in query 13] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'VISIBLE,
                                                        INDEX `bet_idx`' at line 10

2020-11-02 06:24 UTC, mihan007 commented on schema.sql
> +                                                        INDEX `user_idx` (`user_id` ASC) VISIBLE,
[ERROR in query 13] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'VISIBLE,
                                                        INDEX `bet_idx`' at line 10

2020-11-02 06:24 UTC, mihan007 commented on schema.sql
> +                                                        INDEX `item_idx` (`item_id` ASC) VISIBLE,
[ERROR in query 13] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'VISIBLE,
                                                        INDEX `bet_idx`' at line 10

2020-11-02 06:25 UTC, mihan007 commented
@al-galkin 

1. Ошибка с VISIBLE появляется из-за того, что ты используешь функции mysql 8.0 (https://dev.mysql.com/doc/refman/8.0/en/invisible-indexes.html). Согласно заданию https://up.htmlacademy.ru/php/12/check/tasks/1637193/9 скрипт должен корректно отрабатывать на MySQL 5.7. Скорее всего это настройки инструмента проектирования данных, который ты используешь. Поменяй там и локально уменьши версию mysql до 5.7, чтобы проверять импорт на ней

2. Для полей с датой и времени удобнее использовать datetime http://www.mysql.ru/docs/man/DATETIME.html. Это некритично, можно и timestamp, но разрядность уменьшить

3. Непринципиально, но важно знать. В реальном проекте рекомендуется убрать 

CREATE SCHEMA IF NOT EXISTS `yeticave_db` DEFAULT CHARACTER SET utf8 ;
USE `yeticave_db` ;

Пользователь сам должен определять в какую БД этот дамп записывать. И скорее всего название его БД будет отлично от  yeticave_db.

4. Из пункта выше следует, что префикс `yeticave_db` в конструкциях вида CREATE TABLE IF NOT EXISTS `yeticave_db`.`user` надо убрать. Этот префикс явно указывает БД в какой создавать

2020-11-02 08:17 UTC, al-galkin commented
@mihan007 Переписал sql вручную, использовав старые наработки MySQL Workbench

2020-11-03 07:53 UTC, mihan007 commented
@al-galkin прекрасная работы. четко, по ТЗ и видно, что хорошо в теме разобрался.

Предлагаю ее отполировать до идеала. Вот мои рекомендации:
- надо выбрать одно название для полей с датой создания, чтобы не путаться. сейчас там bet_date, creation_date, registration_date. Это все можно заменить на универсальное created_at.
- далее этот created_at можно заполнять средствами базы - она умеет при добавлении записи автоматически это поле прописывать. погугли, я помогу если не найдешь
- еще очень удобно создавать поле updated_at - это дата, когда строка в базе изменилась. ее тоже можно автоматически заполнять через СУБД
- посмотри на использование префиксов. очень редко он нужен. то есть вместо bet_id нужно использовать просто id. category_id сменить на id и аналогично. я не знаю, что у вас в теории, но далее ты будешь разрабатывать с фреймворками, а они по умолчанию ожидают название поля с первичным ключом как id
- еще по префиксам. не надо делать префиксы вида название_таблицы_название_поля. Делай просто title вместо category_title. Далее в запросах может быть 2 title разных таблиц, это нормально. Ты просто в запросе укажешь `название таблицы`.`название поля` и все будет ок.
- если выберешь название created_at, updated_at, то и для других полей с датой используй схожие глаголы. Например, completion_date превратится в completed_at

2020-11-03 07:53 UTC, mihan007 requested changes
Посмотри замечания в https://github.com/htmlacademy-php/1637193-yeticave-12/pull/15#issuecomment-720959693

2020-11-03 11:09 UTC, mihan007 approved these changes

2020-11-03 11:09 UTC, merged