module7-task1
htmlacademy-php/1637193-yeticave-12 pull request #22
Opened 2020-11-30 17:40 UTC by al-galkin

2020-12-01 09:24 UTC, mihan007 commented
1. лучше переименовать functions/data.php в functions/config.php. Название файла как data.php не несет никакой полезной информации и не является обозначением содержимого файла. config подходит лучше.
2. при посещении страницы /sign-up.php появляется ошибка. Необходимо устранить.
```
Notice: Undefined variable: is_auth in /Users/mihan007/Projects/academy-1637193-yeticave-12/templates/layout.php on line 35
```
![image](https://user-images.githubusercontent.com/939122/100718136-07139180-33cc-11eb-9542-a6789af9f0a6.png)
3. На странице sign-up.php согласно https://up.htmlacademy.ru/php/12/project/yeticave#yeti-4-1 должна быть проверка всех полей на заполненность. Сейчас, если я не ввожу ничего, и нажимаю "Зарегистрироваться", то не вижу сообщения об ошибке в поле "Контактные данные"
![image](https://user-images.githubusercontent.com/939122/100718429-61145700-33cc-11eb-9c6a-f906dda52f23.png)
4. После сабмита формы с незаполненным полем "Контактные данные" непонятно, что произошло. Согласно ТЗ должно быть перенаправление на **страницу входа**. Сейчас мы остались на странице регистрации и не появилось информация об ошибке - пустое поле контактных данных
![image](https://user-images.githubusercontent.com/939122/100718679-aafd3d00-33cc-11eb-9be2-8f7daa654b19.png)
5. Неверная валидация пароля. Ввел в него signsign, появилась ошибка "В пароле не должно быть русских букв: допустимы только латинские буквы, цифры и спец. символы". Посмотри на http://itworkarounds.blogspot.com/2011/08/validating-cyrillic-utf8-alphanumeric.html, скорее всего тебе подойдет регулярка **не** \p{Cyrillic}.
6. Пароль ```38vdHmAgnu5^G6han%HPTEgGU``` прошел, это хорошо.
7. После сабмита формы с заполненным полем "Контактные данные" непонятно, что произошло. Согласно ТЗ должно быть перенаправление на **страницу входа**. Сейчас мы остались на странице регистрации и не появилось информация об ошибке - пустое поле контактных данных

2020-12-01 09:24 UTC, mihan007 requested changes

2020-12-01 09:24 UTC, mihan007 commented on functions/check.php
> +    $connect = db_connection();
эту проверку лучше вынести в отдельный валидатор. что-то вроде validate_unique_email

2020-12-01 09:24 UTC, mihan007 commented on functions/check.php
> +        return "Это поле должно быть заполнено: " . $name;
момент 1. для улучшения юзабилити рекомендую тебе передавать сюда не только название поля формы, но и его человекочитаемое название.

Например, вместо validate_filled("name") у тебя будет validate_filled("name", "Имя"). Тогда пользователю будет легче понять в чем ошибка - он будет видеть в сообщении ошибки название поля ровно также как оно указано в форме. 

Я бы вывел вот так
Было "Это поле должно быть заполнено: name"
Стало "Заполните, пожалуйста, поле Имя".

момент 2. В любых сообщениях системы пользователь должен видеть что ему надо сделать, что мы от него хотим. В сообщении об ошибке "Это поле должно быть заполнено: name" не очевидно, что поле надо заполнить. То есть пользователь читает его и задает вопрос "И чо?". В варианте "Заполните, пожалуйста, поле Имя" четко и понятно, что ему делать. 

Аналогично с другими полями. В email у тебя уже верно "Введите корректный e-mail в формате name@post.com"

2020-12-01 09:24 UTC, mihan007 commented on templates/404_page.php
> +    <a href="../index.php">Предлагаем вернуться на главную</a>
лучше абсолютный путь. просто "/index.php". Если данную страницу перемесят по другому адресу - вглубь сайта, например, то твоя ссылка будет некорректной

2020-12-01 09:24 UTC, mihan007 commented on templates/add_lot.php
> +      action="../add.php" method="post" enctype="multipart/form-data">
абсолютный путь

2020-12-01 09:24 UTC, mihan007 commented on templates/layout.php
> +            <a class="main-header__logo" href="../index.php">
абсолютный путь

2020-12-01 09:24 UTC, mihan007 commented on templates/layout.php
> +                            <a href="../sign-up.php">Регистрация</a>
и тут абсолютный

2020-12-01 09:24 UTC, mihan007 commented on templates/layout.php
> +                            <a href="../enter.php">Вход</a>
и тут абсолютный

2020-12-01 09:24 UTC, mihan007 commented on templates/layout.php
> +    <main <?php if($title == TITLE_MAIN_PAGE): ?>class="container"<?php endif; ?>>
так точно не надо делать, сеошники могу title поменять и все сломается. лучше отслеживать url и по нему определять главная это страница или нет. напиши функцию is_index_page и в ней выпиши логику определения главная страница или нет

2020-12-01 09:24 UTC, mihan007 commented on templates/layout.php
> +<script src="../flatpickr.js"></script>
абсолютный

2020-12-01 09:24 UTC, mihan007 commented on templates/layout.php
> +<script src="../script.js"></script>
абсолютный

2020-12-01 09:24 UTC, mihan007 commented on templates/lot_page.php
> +                <img src="../<?= htmlspecialchars($lot['image_url'] ?? '#') ?>" width="730" height="548"
абсолютный

2020-12-01 09:24 UTC, mihan007 commented on templates/main.php
> +                   href="../pages/all-lots.html"><?= htmlspecialchars($category_name['title']); ?></a>
абсолютный

2020-12-01 09:24 UTC, mihan007 commented on templates/registration_page.php
> +    <a class="text-link" href="../enter.php">Уже есть аккаунт</a>
абсолютный

2020-12-01 09:24 UTC, mihan007 commented on templates/registration_page.php
> +<form class="form container <?= empty($errors) ? "" : "form--invalid" ?>" action="../sign-up.php" method="post"
action абсолютный

2020-12-01 09:24 UTC, mihan007 commented on queries.sql
> +-- Увеличение количества символов в поле "Пароль" для сохранения ХЕШ-пароля в БД
лучше в schema.sql унеси. сейчас этот файл у тебя вряд ли будут запускать повторно.

как вариант на вырост предлагаю сделать как в фреймворках. создай папке migrations и в нею перемести текущие файлы по работе с бд. их надо упорядочить по порядку, в котором надо запускать. по итогу у тебя будет папка migrations и в ней файлы
1. 001_schema.sql
2. 002_seed.sql (это переименованный queries.sql, seed - общепринятое название операции по заполнению базы данных данными)
3. 003_alter_users_password.sql - код, который ты тут добавил.

когда ты сделаешь так, то любому человеку на проекте будет понятно, что и в каком порядке надо сделать. а тебе и мне будет легче понимать как ты меняшь бд.

тогда

2020-12-01 16:13 UTC, al-galkin commented on templates/layout.php
> +    <main <?php if($title == TITLE_MAIN_PAGE): ?>class="container"<?php endif; ?>>
@mihan007 поправил на `<?php if (pathinfo($_SERVER['REQUEST_URI'])['basename'] == 'index.php'): ?>class="container"<?php endif; ?>` 
[https://dwweb.ru/page/php/url/002_php_adres_tekuschey_stranitsyi.html#paragraph_2](url)

Насколько корректно?

2020-12-03 14:30 UTC, mihan007 approved these changes

2020-12-03 14:31 UTC, mihan007 commented
отлично!

2020-12-03 14:31 UTC, merged