module7-task2
htmlacademy-php/1637193-yeticave-12 pull request #24
Opened 2020-12-03 15:14 UTC by al-galkin

2020-12-03 15:31 UTC, mihan007 requested changes
надо доделать

2020-12-03 15:31 UTC, mihan007 commented on functions/check.php
> +    $check_sql = "SELECT * FROM users WHERE email = '$check_email'"; // запрос на поиск записи в таблице пользователей по переданному email
не, не. тут надо prepared statements как ты раньше делал. текущий вариант - очень опасный

2020-12-03 15:31 UTC, mihan007 commented on functions/check.php
> +function check_unique_email(mysqli $connect)
тут надо пологичнее назвать. цель же проверить есть ли email в базе.

2020-12-03 15:31 UTC, mihan007 commented on enter.php
> +        if (password_verify($_POST['password'], $user['password'])) {
вообще я бы сделал запросов поменьше - ты получил email и пароль. захэшируй пароль и сделай запрос к базе с введенным email и хэшем пароля. не нашел - ошибка. нашел - авторизовывай.

отдельно проверять есть ли пользователь с емаил в базе не стоит. тем самым твой сервис дает возможность проверить есть ли конкретный емаил на сайте, а это неправильно. такая информация может использоваться в каких-то плохих целях, например, найдут емаил популярного юзера и проверят, что он у тебя есть. ну и начнут ломать.

так что самая простая бинарная логика здесь подходит
1. есть пользователь - авторизуем
2. не пользователя с емаил и хэшом - пишем ошибку "пользователь с указанными email и паролем не найден. попробуйте еще раз или восстановите пароль" (не знаю будет ли в рамках этого тз восстановление пароля, но обычно этот сценарий делают).

2020-12-04 14:01 UTC, al-galkin commented on enter.php
> +        if (password_verify($_POST['password'], $user['password'])) {
@mihan007 корявое требование в п. 4.2. https://up.htmlacademy.ru/php/12/project/yeticave#yeti-4-2
Пока обезличил текст ошибок, но логика осталась +- та же. Посмотри, интересно твое мнение, как можно "резать" без потерь логики

2020-12-06 09:25 UTC, mihan007 commented on enter.php
> +        if (password_verify($_POST['password'], $user['password'])) {
@al-galkin 
1. не увидел в чем корявость. поясни?
2. неверная валидация. если поле e-mail пустое, то ожидается вывод сообщения об ошибке "Заполните поле e-mail". Сейчас выводится иное
![image](https://user-images.githubusercontent.com/939122/101276446-f42f0180-37bd-11eb-993f-308296c0d675.png)
3. Если пользователь ввёл неверные данные аккаунта (несуществующий пользователь или неверный пароль), то в сообщении **над** формой должен быть текст «Вы ввели неверный email/пароль». Сейчас отображается **под** формой
![image](https://user-images.githubusercontent.com/939122/101276460-16288400-37be-11eb-9698-213537ec95dd.png)

2020-12-06 09:35 UTC, mihan007 commented
Замечания
1. https://github.com/htmlacademy-php/1637193-yeticave-12/pull/24#discussion_r536996981
остальные требования
- [x] Создайте новую страницу с формой входа. Вёрстку для формы нужно взять из файла pages/login.html.
- [ ] При отправке формы проверяйте заполненность двух полей. Если поле не было заполнено, то следует показать ошибку - https://github.com/htmlacademy-php/1637193-yeticave-12/pull/24#discussion_r536996981
- [x] Если форма прошла валидацию, то выполнить процесс аутентификации и переадресовать пользователя на главную страницу. Если пользователь ввёл неверный пароль, то показать ошибку внутри контейнера с полем «Пароль» и текстом «Вы ввели неверный пароль».
- [x] В шапке сайта показывать имя пользователя, если есть открытая сессия, иначе показывать ссылки «Регистрация» и «Вход». Ссылка «Вход» должна вести на страницу входа.
- [x] На странице lot.php скрывать блок добавления ставки для анонимных пользователей.
- [ ] Добавить новый сценарий: logout.php. Сценарий должен обнулять пользовательскую сессию и переадресовывать на главную страницу - **нарушено тз. сама страница выхода мне понравилась, но по ТЗ она не нужна**
- [x] Добавить адрес этой страницы в ссылку «Выход» под именем пользователя.
- [ ] Я бы добавил еще при посещении /logout.php неавторизованный пользователь должен автоматически переадресовывать на главную. Сейчас у тебя для неавторизованного пользователя открывается шаблон этой страницы с сообщением, что пользователь разлгонилися, но это неправда
- [ ] Закрыть доступ к странице add.php для анонимных пользователей. При попытке обращения к этой странице анонимному пользователю должен возвращаться HTTP-код ответа 403. - **не выполнено. я зашел на страницу в режиме инкогнито и вижу форму добавления. ожидается - показ 403 ошибки**
![image](https://user-images.githubusercontent.com/939122/101276628-4886b100-37bf-11eb-97ed-ab73c52181c0.png)
- [ ] По такому же принципу для залогиненных пользователей надо закрыть страницу регистрации. - **не выполнено. я авторизован и захожу на enter.php. выполняется переадресация на главную. ожидается - показ 403 ошибки**

2020-12-06 09:36 UTC, mihan007 requested changes
смотри комментарий под PR

2020-12-06 13:58 UTC, mihan007 approved these changes

2020-12-06 13:58 UTC, merged